# Generated by Django 4.1.1 on 2022-09-30 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='project_upload_images')),
                ('category', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=50)),
                ('description', models.TextField(default='description', max_length=1000)),
                ('slug', models.SlugField(default='slug', unique=True)),
                ('image', models.ImageField(upload_to='project_images')),
                ('project_link', models.URLField(blank=True, default='url', max_length=250, null=True)),
                ('githublink', models.URLField(blank=True, default='url', max_length=250, null=True)),
                ('category', models.ForeignKey(default=40, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='blog_images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to='portfolioapp.category')),
            ],
        ),
    ]
