# Generated by Django 4.1.1 on 2022-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_home_alter_blog_category_alter_project_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='contact_images')),
                ('image2', models.ImageField(upload_to='contact_images')),
            ],
        ),
    ]
