# Generated by Django 4.1.1 on 2023-12-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
